### ISSUE TITLE
Help building and running in windows

### ISSUE THREAD

**Issue by sudarshann** [ArduPilot/APWeb#10]
I am looking for an way to building this project in windows. Can anyone assist me with on how and what tools do I need to build this with windows

Thanks

**Comment by magicrub** [comment]
@rmackay9 should know about this

**Comment by sudarshann** [comment]
@magicrub @rmackay9 
after several hours of research finally I managed to build a version for windows
webserver works fine

But I am unable to configure the port for serial


my device is at com port 3
"com3: No such file or directory
Failed to open mavlink serial port com3"


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Also Another Case 
I also have Ubuntu Xenial under windows sub system of Linux in windows 10
I am able to build and run the app
but my the web ui is not getting any data from Ardupilot and I get no errors except web ui is blank without any data

**Comment by magicrub** [comment]
I think what you're looking for are changes to the wiki docs, rather than the library TODO bug tracker issue list. Is that right? Have you tried the forums for help? discuss.ardupilot.org

**Comment by davidbuzz** [comment]
this is the wrong place to ask for help.  please ask for help at http://discuss.ardupilot.org  and once you've solved the issue, please update the documentation at https://github.com/ArduPilot/ardupilot_wiki/     If you find that changes are required to APWeb itself to make it build on windows, and know specifically what those changes are , please re-open this issue.
